// <auto-generated />
using System;
using AVEquipmentManager.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVEquipmentManager.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607000000_AddCategoryAndAcquisitions")]
    partial class AddCategoryAndAcquisitions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("AVEquipmentManager.Shared.Models.Equipment", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime?>("ArchivedAt").HasColumnType("TEXT");
                    b.Property<int>("Category").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<DateTime>("DateInstalled").HasColumnType("TEXT");
                    b.Property<int>("ExpectedLifeInYears").HasColumnType("INTEGER");
                    b.Property<bool>("IsArchived").HasColumnType("INTEGER");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("TEXT");
                    b.Property<string>("RoomName").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("SerialNumber").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                    b.Property<int>("Status").HasColumnType("INTEGER");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("TEXT");

                    b.HasKey("Id");
                    b.HasIndex("SerialNumber").IsUnique();
                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("AVEquipmentManager.Shared.Models.Acquisition", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("Category").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<DateTime?>("DeployedAt").HasColumnType("TEXT");
                    b.Property<int?>("DeployedEquipmentId").HasColumnType("INTEGER");
                    b.Property<string>("IntendedRoom").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("ItemName").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("TEXT");
                    b.Property<DateTime?>("OrderedAt").HasColumnType("TEXT");
                    b.Property<string>("PurchaseOrderNumber").HasMaxLength(100).HasColumnType("TEXT");
                    b.Property<int>("Quantity").HasColumnType("INTEGER");
                    b.Property<DateTime?>("ReceivedAt").HasColumnType("TEXT");
                    b.Property<string>("RequestedBy").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<int>("Status").HasColumnType("INTEGER");
                    b.Property<decimal?>("UnitCost").HasColumnType("TEXT");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("TEXT");
                    b.Property<string>("Vendor").HasMaxLength(200).HasColumnType("TEXT");

                    b.HasKey("Id");
                    b.HasIndex("DeployedEquipmentId");
                    b.ToTable("Acquisitions");
                });

            modelBuilder.Entity("AVEquipmentManager.Shared.Models.Acquisition", b =>
                {
                    b.HasOne("AVEquipmentManager.Shared.Models.Equipment", "DeployedEquipment")
                        .WithMany()
                        .HasForeignKey("DeployedEquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("DeployedEquipment");
                });

            modelBuilder.Entity("AVEquipmentManager.Shared.Models.Disposal", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("EquipmentId").HasColumnType("INTEGER");
                    b.Property<string>("Reason").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<int>("Method").HasColumnType("INTEGER");
                    b.Property<int>("Status").HasColumnType("INTEGER");
                    b.Property<string>("RequestedBy").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("ApprovedBy").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("DisposalNotes").HasMaxLength(1000).HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<DateTime?>("ApprovedAt").HasColumnType("TEXT");
                    b.Property<DateTime?>("DisposedAt").HasColumnType("TEXT");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("EquipmentId");
                    b.ToTable("Disposals");
                });

            modelBuilder.Entity("AVEquipmentManager.Shared.Models.Disposal", b =>
                {
                    b.HasOne("AVEquipmentManager.Shared.Models.Equipment", "Equipment")
                        .WithMany().HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("AVEquipmentManager.Shared.Models.Ticket", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("TEXT");
                    b.Property<string>("Description").HasMaxLength(2000).HasColumnType("TEXT");
                    b.Property<int>("EquipmentId").HasColumnType("INTEGER");
                    b.Property<int>("Type").HasColumnType("INTEGER");
                    b.Property<int>("Priority").HasColumnType("INTEGER");
                    b.Property<int>("Status").HasColumnType("INTEGER");
                    b.Property<string>("ReportedBy").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("AssignedTo").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("Resolution").HasMaxLength(2000).HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("TEXT");
                    b.Property<DateTime?>("ResolvedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("EquipmentId");
                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("AVEquipmentManager.Shared.Models.Ticket", b =>
                {
                    b.HasOne("AVEquipmentManager.Shared.Models.Equipment", "Equipment")
                        .WithMany().HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("AVEquipmentManager.Shared.Models.User", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Role").IsRequired().HasMaxLength(20).HasDefaultValue("Student").HasColumnType("TEXT");
                    b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("Username").IsUnique();
                    b.ToTable("Users");
                });

            modelBuilder.Entity("AVEquipmentManager.Shared.Models.Staff", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime?>("ArchivedAt").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("Department").HasMaxLength(150).HasColumnType("TEXT");
                    b.Property<string>("Email").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("EmployeeId").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                    b.Property<bool>("IsArchived").HasColumnType("INTEGER");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("Phone").HasMaxLength(50).HasColumnType("TEXT");
                    b.Property<string>("RoomNumber").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("EmployeeId").IsUnique();
                    b.ToTable("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
